### ISSUE TITLE
About Face 2.0: The Essentials of Interaction Design

### ISSUE THREAD

**Issue by agquarx** [ericelliott/the-software-developers-library#3]
https://books.google.pl/books?id=blLjIS9z31QC&q=about+face+interface+book&dq=about+face+interface+book&hl=en&sa=X&redir_esc=y

**Comment by ericelliott** [comment]
Thanks.

I think this is out of scope for this particular list. I could write another list equally long about UX design.

**Comment by deepak** [comment]
maybe add a section on 'Introduction to UX for Software Developers' ?

**Comment by ericelliott** [comment]
That's not a terrible idea, but we'll need more books. "Don't Make Me Thing" and "The Design of Every Day Things" spring immediately to mind. What else?

**Comment by deepak** [comment]
I have read "Don't Make Me Think". and would recommend it

the other book, which i have read and recommend is

- Design Is a Job by Mike Monteiro, A List Apart

but is more business oriented. not UX

other books, but which i have not read are:

- The Inmates Are Running the Asylum by Alan Cooper - Why High Tech Products Drive Us Crazy and How to Restore the Sanity
- User Interface Design for Programmers by Joel Spolsky
- Rocket Surgery Made Easy by Steve Krug
- Designing Interfaces by Jenifer Tidwell - Patterns for Effective Interaction Design
- Programming as if People Mattered by Nathaniel S. Borenstein
- Lean UX by Jeff Gothelf & Josh Seiden - Applying Lean Principles to Improve User Experience
- UX for Lean Startups by Laura Klein - Faster, Smarter User Experience Research and Design

**Comment by ericelliott** [comment]
I've only read "Lean UX", from that list. I wouldn't know what to recommend.

"Design is a Job" sounds out of scope for most lots of developers...

**Comment by deepak** [comment]
my vote goes for:
- Don't Make Me Think (I have read) 
- The Design of Every Day Things (I have not read)
