### ISSUE TITLE
add The Cathedral & the Bazaar by Eric S. Raymond (ESR) 

### ISSUE THREAD

**Issue by deepak** [ericelliott/the-software-developers-library#5]
do you want to add [The Cathedral & the Bazaar by Eric S. Raymond (ESR) - Musings on Linux and Open Source by an Accidental Revolutionary, 2001](http://www.amazon.com/The-Cathedral-Bazaar-Accidental-Revolutionary/dp/0596001088/)

not sure what section it will come under, maybe create a new one called history ?

**Comment by ericelliott** [comment]
I think that would fit nicely in "Productivity & Principles"

**Comment by deepak** [comment]
@ericelliott sent PR. not sure about the link structure. so copied one from the existing links

**Comment by ericelliott** [comment]
Yep. Commented for the link fix...

**Comment by deepak** [comment]
@ericelliott fixed
